### ISSUE TITLE
大佬  安卓完美   但是ios报错

### ISSUE THREAD

**Issue by R10burning** [xiehui999/react-native-webview-plugin#1]
Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined

**Comment by hejun041** [comment]
postMessage 可用吗

**Comment by R10burning** [comment]
@hejun041   好像不行  你可以用吗

**Comment by hejun041** [comment]
我改了下源码，可以用了。但是还有点小问题

**Comment by R10burning** [comment]
@hejun041  大佬  可以告诉我怎么改的吗 。。。脑壳痛啊 不懂Android

**Comment by hejun041** [comment]
注意看index.android.js 里面的是event 还是event.nativeEvent,每个方法都检查一下

**Comment by R10burning** [comment]
@hejun041  没有index.android.js这个文件啊   我就是postMessage的时候报不是一个方法

**Comment by R10burning** [comment]
方便加个QQ吗

**Comment by hejun041** [comment]
@R10burning 你QQ多少

**Comment by R10burning** [comment]
@hejun041  790309793

**Comment by xiehui999** [comment]
@R10burning @hejun041 不需要改代码啊，使用postMessage 的话需要通过webviewRef，目前我这边没有重写这个方法，所以通过ref获取引用是没这个函数的，需要通过webviewRef 获取RN 引用发送，readme.md里有说明。
