### ISSUE TITLE
android平台编译报错

### ISSUE THREAD

**Issue by gitSirzh** [xiehui999/react-native-webview-plugin#7]
:react-native-webview-plugin:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/jszh/react-native-project/qianmicashloanNew/node_modules/react-native-webview-plugin/android/src/main/java/com/webview/code4android/WebViewPackage.java:13: 错误: WebViewPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()
public class WebViewPackage implements ReactPackage {
       ^
/Users/jszh/react-native-project/qianmicashloanNew/node_modules/react-native-webview-plugin/android/src/main/java/com/webview/code4android/WebViewManager.java:99: 错误: 找不到符号
            if (mUrlPrefixesForDefaultIntent != null && mUrlPrefixesForDefaultIntent.size() > 0) {
                ^
  符号:   变量 mUrlPrefixesForDefaultIntent
  位置: 类 CustomWebViewClient
/Users/jszh/react-native-project/qianmicashloanNew/node_modules/react-native-webview-plugin/android/src/main/java/com/webview/code4android/WebViewManager.java:99: 错误: 找不到符号
            if (mUrlPrefixesForDefaultIntent != null && mUrlPrefixesForDefaultIntent.size() > 0) {
                                                        ^
  符号:   变量 mUrlPrefixesForDefaultIntent
  位置: 类 CustomWebViewClient
/Users/jszh/react-native-project/qianmicashloanNew/node_modules/react-native-webview-plugin/android/src/main/java/com/webview/code4android/WebViewManager.java:101: 错误: 找不到符号
                        mUrlPrefixesForDefaultIntent.toArrayList();
                        ^
  符号:   变量 mUrlPrefixesForDefaultIntent
  位置: 类 CustomWebViewClient
4 个错误
:react-native-webview-plugin:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview-plugin:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by gitSirzh** [comment]
我执行 react-native run-android 报错信息如上

**Comment by xiehui999** [comment]
> 我执行 react-native run-android 报错信息如上

你Application中没加入这个Module
